# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:  个人博客
subtitle: 分享技术，品味人生
name: 吴康丽 
email: ityouknow@126.com
description: 本站是吴康丽的技术分享博客。内容涵盖生活故事、前端技术、中间件使用、系统监控等相关的研究与知识分享。
keywords: wudaxia,NodeJS,vue,mongodb,小程序,express
encoding: "utf-8"
favicon: favicon.ico 

repository: wudaxia/wudaxia.github.io
github_url: https://github.com/wudaxia
url: https://wudaxia.github.io
enforce_ssl: ityouknow.com

## Gem
plugins:
  - jekyll-paginate
  - jekyll-geo-pattern
  - rouge
  - kramdown
  - jekyll-github-metadata

# Build settings
markdown: kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"

source:      .
destination: ./_site

quiet:    false
defaults: []

kramdown:
  input: GFM
  enable_coderay: true
  syntax_highlighter: rouge

syntax_highlighter_opts:
   coderay_line_numbers:  nil

# Pagination
paginate: 12
paginate_path: 'page:num'

# Navigation. top menu list
menus:

  -
    href: /python.html
    label: Python  
    target: _self

  -
    href: /it.html
    label: IT
    target: _self

  -
    href: /zsxq.html
    label: 星球
    target: _self   

  -
    href: /life.html
    label: 故事
    target: _self

  -
    href: /arch.html
    label: 架构
    target: _self

  -
    href: /link.html
    label: 友链
    target: _self



# Navigation. main menu list
navs:

  -
    href: /
    label: Home

  -
    href: /vuejs.html
    label: VUE
    target: _self

  -
    href: /miniProgram.html
    label: miniProgram
    target: _self

  -
    href: /it.html
    label: NodeJS
    target: _self

  -
    href: /archives.html
    label: Archives
    target: _self

  -
    href: /about.html
    label: About
    target: _self


# labels. my blog key words
labels:

  -
    href: /payment.html
    label: 支付     
    target: _self


  -
    href: /mongodb.html
    label: MongoDB
    target: _blank


  -
    href: /open-source.html
    label: Code  
    target: _blank

  -
    href: /gitchat.html
    label: Chat
    target: _blank

  -
    href: /geektime.html
    label: 极客
    target: _blank


# selected articles
classes:

  -
    href: /life.html
    name: 我的故事
    describe: 生活就是故事，故事就是生活

  -
    href: /arch.html
    name: 前端工程师之路
    describe: 一个前端工程师的自我修养

  # -
  #   href: /java.html
  #   name: Java 系列文章
  #   describe: Java 之根基，Java 程序员必学


# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# Sidebar to show popular repo
side_bar_repo_limit: 6 # Number of repos to show

# Google Analytics
# analytics :
# provider : google
#   google :
#     tracking_id : ''  # ex. UA-72165600-X


# For about.html. Fell free to create your own!
skill_software_keywords: [Java, MySQL, Oracle, Design Patterns]
skill_j2ee_keywords: [Spring, Struct, Hibernet, MyBatis, JSP]
skill_web_keywords: [HTML, CSS, JS, JQuery, Ajax, NodeJS, ExpressJS, MongoDB, Redis, PHP,  Boostrap]
skill_mobile_app_keywords: [vuejs, hyhird app]


# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: wudaxia
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: wudaxia
    repo: blog-comments
    oauth:
        client_id: 0c736fbc49e7e559e78d
        client_secret: 20b2edf4f989fc735eaa86a535651b2b40950a05
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: wudaxia
    repo: blog-comments
    clientID: 0c736fbc49e7e559e78d
    clientSecret: 20b2edf4f989fc735eaa86a535651b2b40950a05
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : true
